env:
  browser: true
  es2021: true
extends:
  - standard-with-typescript
  - plugin:react/recommended
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - simple-import-sort
rules: {
  "react/prop-types": "off",
  "react/react-in-jsx-scope": "off",
  "@typescript-eslint/no-non-null-assertion": "off",
  'simple-import-sort/imports': 'error',
  'simple-import-sort/exports': 'error'
}
settings: 
  react:
    version: "detect"
