env:
  browser: true
  es2021: true
plugins:
  - simple-import-sort
extends:
  - standard-with-typescript
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  {
    '@typescript-eslint/no-non-null-assertion': 'off',
    'simple-import-sort/imports': 'error',
    'simple-import-sort/exports': 'error'
  }
