openapi: 3.0.0
info:
  title: Wine Century Backend Code
  description: backend code for the wine century website
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /admin/login:
    post:
      summary: Login as an admin
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdminLoginRequest'
      responses:
        '200':
          description: Session token for admin
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdminLoginResponse'
        '401':
          description: Admin not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Admin not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /admin/register:
    post:
      summary: Register an admin
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdminSignupRequest'
      responses:
        '201':
          description: Session token for admin
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdminSignupResponse'
        '401':
          description: Admin not authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Admin already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /admin/products:
    post:
      summary: Create a product
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProductRequest'
      responses:
        '201':
          description: Product created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateProductResponse'
        '401':
          description: Admin not authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Product already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /admin/users:
    get:
      summary: List users
      parameters:
        - in: query
          name: limit
          required: true
          schema:
            type: integer
            minimum: 1
          description: Limit of users to get
        - in: query
          name: offset
          required: true
          schema:
            type: integer
            minimum: 0
          description: Offset of users to get
      responses:
        '200':
          description: Users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserListResponse'
        '401':
          description: Admin not authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /admin/users/{userID}:
    put:
      summary: Update user
      parameters:
        - in: path
          name: userID
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to update
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EditUserRequest'
      responses:
        '200':
          description: Edited successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EditUserResponse'
        '401':
          description: Admin not authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      summary: Delete user
      parameters:
        - in: path
          name: userID
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to delete
      responses:
        '204':
          description: Deleted successfully
        '401':
          description: Admin not authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    AdminLoginRequest:
      type: object
      properties:
        email:
          type: string
          description: Admin email
        password:
          type: string
          description: Admin password
      required:
        - email
        - password

    AdminLoginResponse:
      type: object
      properties:
        token:
          type: string
          description: Bearer Token for API Use

    AdminSignupRequest:
      type: object
      properties:
        firstName:
          type: string
          description: Admin first name
        lastName:
          type: string
          description: Admin last name
        email:
          type: string
          description: Admin email
        password:
          type: string
          description: Admin password
      required:
        - firstName
        - lastName
        - email
        - password

    AdminSignupResponse:
      type: object
      properties:
        id:
          type: integer
          description: Admin id
        firstName:
          type: string
          description: Admin first name
        lastName:
          type: string
          description: Admin last name
        email:
          type: string
          description: Admin email
        createdAt:
          type: string
        updatedAt:
          type: string
      required:
        - id
        - firstName
        - lastName
        - email
        - createdAt
        - updatedAt

    CreateProductRequest:
      type: object
      properties:
        name:
          type: string
          description: Product name
        details:
          type: string
          description: Product details
        price:
          type: number
          description: Product price
      required:
        - name
        - details
        - price

    CreateProductResponse:
      type: object
      properties:
        id:
          type: integer
          description: Product id
        name:
          type: string
          description: Product name
        details:
          type: string
          description: Product details
        price:
          type: number
          description: Product price
        createdAt:
          type: string
        updatedAt:
          type: string
      required:
        - id
        - name
        - details
        - price
        - createdAt
        - updatedAt

    EditUserRequest:
      type: object
      properties:
        firstName:
          type: string
          description: Admin first name
        lastName:
          type: string
          description: Admin last name
        email:
          type: string
          description: Admin email
      required:
        - firstName
        - lastName
        - email

    EditUserResponse:
      type: object
      properties:
        id:
          type: integer
          description: Admin id
        firstName:
          type: string
          description: Admin first name
        lastName:
          type: string
          description: Admin last name
        email:
          type: string
          description: Admin email
        createdAt:
          type: string
        updatedAt:
          type: string
      required:
        - id
        - firstName
        - lastName
        - email
        - createdAt
        - updatedAt

    UserListResponse:
      type: object
      properties:
        users:
          type: array
        hasMore:
          type: boolean
      required:
        - users
        - hasMore

    ErrorResponse:
      type: object
      properties:
        errorCode:
          type: string
        errorMessage:
          type: string
