openapi: 3.0.0
info:
  title: Wine Century Backend Code
  description: backend code for the wine century website
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /admin/login:
    post:
      summary: Login as an admin
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdminLoginRequest'
      responses:
        '200':
          description: Session token for admin
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/AdminLoginResponse'
        '404':
          description: Admin not found
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/AdminLoginResponse'


components:
  schemas:
    AdminLoginRequest:
      type: object
      properties:
        email:
          type: string
          description: Admin email
        password:
          type: string
          description: Admin password
      required:
        - email
        - password

    AdminLoginResponse:
      type: object
      properties:
        token:
          type: string
          description: Bearer Token for API Use
    
    ErrorResponse:
      type: object
      properties:
        errorCode:
          type: string
        errorMessage:
          type: string
